class SnookrEvent {
}

SnookrEvent.SHOOT_FIRED = 'SHOOT_FIRED';
SnookrEvent.BALLS_STOPPED = 'BALLS_STOPPED';
SnookrEvent.REPAINT = 'REPAINT';
SnookrEvent.SHOT_ATTEMPT = 'SHOT_ATTEMPT';
SnookrEvent.MOUSE_MOVED = 'MOUSE_MOVED';
SnookrEvent.SCORE_CHANGED = 'SCORE_CHANGED';
SnookrEvent.PLAYER_CHANGED = 'PLAYER_CHANGED';
SnookrEvent.RULE_CHANGED = 'RULE_CHANGED';
SnookrEvent.GAME_OVER = 'GAME_OVER';
SnookrEvent.NEXT_RULE_CHOICE = 'NEXT_RULE_CHOICE';
SnookrEvent.NEXT_RULE_CHOSEN = 'NEXT_RULE_CHOSEN';
SnookrEvent.BALL_POTTED = 'BALL_POTTED';
SnookrEvent.RIGHT_BALL_POTTED = 'RIGHT_BALL_POTTED';
SnookrEvent.WRONG_BALL_POTTED = 'WRONG_BALL_POTTED';
SnookrEvent.BREAK_CHANGED = 'BREAK_CHANGED';
SnookrEvent.SNOOKER_CREATED = 'SNOOKER_CREATED';
SnookrEvent.CUE_HITS_BALL = 'CUE_HITS_BALL';
SnookrEvent.BALL_HITS_BALL = 'BALL_HITS_BALL';
SnookrEvent.BALL_HITS_POCKET = 'BALL_HITS_POCKET';
SnookrEvent.ROLLBACK_REQUESTED = 'ROLLBACK_REQUESTED';