class SnookrEvent {
}

SnookrEvent.BALLS_STOPPED = 'BALLS_STOPPED';
SnookrEvent.RULE_CHANGED = 'RULE_CHANGED';
SnookrEvent.NEXT_RULE_CHOICE = 'NEXT_RULE_CHOICE';
SnookrEvent.BALL_POTTED = 'BALL_POTTED';
SnookrEvent.RIGHT_BALL_POTTED = 'RIGHT_BALL_POTTED';
SnookrEvent.WRONG_BALL_POTTED = 'WRONG_BALL_POTTED';
SnookrEvent.SNOOKER_CREATED = 'SNOOKER_CREATED';
SnookrEvent.BALL_HITS_BALL = 'BALL_HITS_BALL';
SnookrEvent.BALL_HITS_POCKET = 'BALL_HITS_POCKET';
SnookrEvent.CUE_HITS_BALL = 'CUE_HITS_BALL';
